# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ScreenNeuroPharm
email: info@screenneuropharm.com
description: > # this means to ignore newlines until "baseurl:"
  "Screen NeuroPharm offers devices to engineer in vitro cell culture for drug screening.""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://screenneuropharm.com" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: ScreenNeuroPharm
address_line: Via All'Opera Pia 13, Genova, 16145, Italy
#telephone_number: 1.800.245.356
#fax_number: 1.800.245.357
company_email: info@screenneuropharm.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2850.4509586550216!2d8.956125215522237!3d44.40339117910275!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12d343a2d09ae3e1%3A0x7cd1d94dc56fb40d!2sVia%20All&#39;Opera%20Pia%2C%2013%2C%2016145%20Genova%20GE!5e0!3m2!1sit!2sit!4v1603041372408!5m2!1sit!2sit
# Social Link
facebook_link: https://www.facebook.com/ScreenNeuroPharm/
twitter_link: https://twitter.com/ScreenNeuroPhar
linkedin_link: https://www.linkedin.com/company/screeneuropharm/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/